export const DELETE_INGREDIENT: 'DELETE_INGREDIENT' = 'DELETE_INGREDIENT';
export const CHANGE_ITEM_POSITION: 'CHANGE_ITEM_POSITION' = 'CHANGE_ITEM_POSITION';

export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';

export const SET_INGREDIENT_ITEM: 'SET_INGREDIENT_ITEM' = 'SET_INGREDIENT_ITEM';
export const DELETE_INGREDIENT_ITEM: 'DELETE_INGREDIENT_ITEM' = 'DELETE_INGREDIENT_ITEM';

export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';

export const INCREASE_TOTAL_PRICE: 'INCREASE_TOTAL_PRICE' = 'INCREASE_TOTAL_PRICE';
export const DECREASE_TOTAL_PRICE: 'DECREASE_TOTAL_PRICE' = 'DECREASE_TOTAL_PRICE';

export const DELETE_CONSTRUCTOR_ITEMS: 'DELETE_ORDER_NUMBER' = 'DELETE_ORDER_NUMBER';

export const SET_ORDER_NUMBER: 'SET_ORDER_NUMBER' = 'SET_ORDER_NUMBER';
export const SET_ORDER_DATA: 'SET_ORDER_DATA' = 'SET_ORDER_DATA';
export const DELETE_ORDER_NUMBER: 'DELETE_ORDER_NUMBER' = 'DELETE_ORDER_NUMBER';

export const TAB_SWITCH: 'TAB_SWITCH' = 'TAB_SWITCH';

export const SET_AUTH_CHECKED: 'SET_AUTH_CHECKED' = 'SET_AUTH_CHECKED';
export const SET_USER: 'SET_USER' = 'SET_USER';