export const DELETE_INGREDIENT: 'DELETE_INGREDIENT' = 'DELETE_INGREDIENT';
export const CHANGE_ITEM_POSITION: 'CHANGE_ITEM_POSITION' = 'CHANGE_ITEM_POSITION';

export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';

export const SET_INGREDIENT_ITEM: 'SET_INGREDIENT_ITEM' = 'SET_INGREDIENT_ITEM';
export const DELETE_INGREDIENT_ITEM: 'DELETE_INGREDIENT_ITEM' = 'DELETE_INGREDIENT_ITEM';
export const ADD_BUN_INGREDIENT: 'ADD_BUN_INGREDIENT' = 'ADD_BUN_INGREDIENT';
export const ADD_MAIN_INGREDIENT: 'ADD_MAIN_INGREDIENT' = 'ADD_MAIN_INGREDIENT';

export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';

export const INCREASE_TOTAL_PRICE: 'INCREASE_TOTAL_PRICE' = 'INCREASE_TOTAL_PRICE';
export const DECREASE_TOTAL_PRICE: 'DECREASE_TOTAL_PRICE' = 'DECREASE_TOTAL_PRICE';

export const DELETE_CONSTRUCTOR_ITEMS: 'DELETE_ORDER_NUMBER' = 'DELETE_ORDER_NUMBER';

export const SET_ORDER_NUMBER: 'SET_ORDER_NUMBER' = 'SET_ORDER_NUMBER';
export const SET_ORDER_DATA: 'SET_ORDER_DATA' = 'SET_ORDER_DATA';
export const DELETE_ORDER_NUMBER: 'DELETE_ORDER_NUMBER' = 'DELETE_ORDER_NUMBER';

export const TAB_SWITCH: 'TAB_SWITCH' = 'TAB_SWITCH';

export const SET_AUTH_CHECKED: 'SET_AUTH_CHECKED' = 'SET_AUTH_CHECKED';
export const SET_USER: 'SET_USER' = 'SET_USER';


export const WS_FEED_CONNECTION_START: 'WS_FEED_CONNECTION_START' = 'WS_FEED_CONNECTION_START';
export const WS_FEED_CONNECTION_SUCCESS: 'WS_FEED_CONNECTION_SUCCESS' = 'WS_FEED_CONNECTION_SUCCESS'; 
export const WS_FEED_CONNECTION_ERROR: 'WS_FEED_CONNECTION_ERROR' = 'WS_FEED_CONNECTION_ERROR';
export const WS_FEED_CONNECTION_CLOSED: 'WS_FEED_CONNECTION_CLOSED' = 'WS_FEED_CONNECTION_CLOSED';
export const WS_FEED_CONNECTION_STOP: 'WS_FEED_CONNECTION_STOP' = 'WS_FEED_CONNECTION_STOP';
export const WS_FEED_GET_MESSAGE: 'WS_FEED_GET_MESSAGE' = 'WS_FEED_GET_MESSAGE';
export const WS_FEED_SEND_MESSAGE: 'WS_FEED_SEND_MESSAGE' = 'WS_FEED_SEND_MESSAGE';

export const WS_USER_CONNECTION_START: 'WS_USER_CONNECTION_START' = 'WS_USER_CONNECTION_START';
export const WS_USER_CONNECTION_SUCCESS: 'WS_USER_CONNECTION_SUCCESS' = 'WS_USER_CONNECTION_SUCCESS'; 
export const WS_USER_CONNECTION_ERROR: 'WS_USER_CONNECTION_ERROR' = 'WS_USER_CONNECTION_ERROR';
export const WS_USER_CONNECTION_CLOSED: 'WS_USER_CONNECTION_CLOSED' = 'WS_USER_CONNECTION_CLOSED';
export const WS_USER_CONNECTION_STOP: 'WS_USER_CONNECTION_STOP' = 'WS_USER_CONNECTION_STOP';
export const WS_USER_GET_MESSAGE: 'WS_USER_GET_MESSAGE' = 'WS_USER_GET_MESSAGE';
export const WS_USER_SEND_MESSAGE: 'WS_USER_SEND_MESSAGE' = 'WS_USER_SEND_MESSAGE';